# Generated by Django 5.2.1 on 2025-06-02 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kanji', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='characters/')),
            ],
        ),
        migrations.CreateModel(
            name='Quirk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='characters.character')),
            ],
            options={
                'verbose_name_plural': 'Aliases',
            },
        ),
        migrations.CreateModel(
            name='CharacterAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.affiliation')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='affiliations',
            field=models.ManyToManyField(through='characters.CharacterAffiliation', to='characters.affiliation'),
        ),
        migrations.CreateModel(
            name='CharacterQuirk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('quirk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.quirk')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='quirks',
            field=models.ManyToManyField(through='characters.CharacterQuirk', to='characters.quirk'),
        ),
    ]
