# Generated by Django 5.2.1 on 2025-05-31 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quirk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hero_name', models.CharField(blank=True, max_length=100)),
                ('affiliation', models.CharField(max_length=100)),
                ('quirk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.quirk')),
            ],
        ),
    ]
