# Generated by Django 5.2.1 on 2025-05-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quirk',
            name='image',
            field=models.ImageField(default=None, upload_to='characters/'),
        ),
    ]
