# Generated by Django 5.2.1 on 2025-05-31 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_quirk_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='character',
            name='affiliation',
        ),
        migrations.RemoveField(
            model_name='character',
            name='quirk',
        ),
        migrations.RemoveField(
            model_name='quirk',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quirk',
            name='image',
        ),
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, upload_to='characters/'),
        ),
        migrations.AddField(
            model_name='character',
            name='kanji',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quirk',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='CharacterAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.affiliation')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='affiliations',
            field=models.ManyToManyField(through='characters.CharacterAffiliation', to='characters.affiliation'),
        ),
        migrations.CreateModel(
            name='CharacterQuirk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('quirk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.quirk')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='quirks',
            field=models.ManyToManyField(through='characters.CharacterQuirk', to='characters.quirk'),
        ),
    ]
