# Generated by Django 5.2.1 on 2025-05-31 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_affiliation_remove_character_affiliation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='hero_name',
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='characters.character')),
            ],
        ),
    ]
